### PR TITLE
Further rewriting of the Writing Styles section

### PR DESCRIPTION
**Pull request by TitusNemeth**
***
<a href="https://pr-preview.s3.amazonaws.com/TitusNemeth/alreq/pull/238.html" title="Last updated on Nov 6, 2020, 2:49 PM UTC (c0e0cdd)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/alreq/238/368d8eb...TitusNemeth:c0e0cdd.html" title="Last updated on Nov 6, 2020, 2:49 PM UTC (c0e0cdd)">Diff</a>

### CODE REVIEW

**Comment by shervinafshar** [comment]
Thanks for the edits @TitusNemeth. I'm assuming that we could cite your book for the edits made to this section. Is that accurate? I checked and we don't have your book in the [list of reference](https://docs.google.com/spreadsheets/d/137j59fPt1nkl0h6O72SR50SX3MHk0lWzmqcEaAmo1zM/edit#gid=0). Do let me know and I will add the information for [this edition](http://www.worldcat.org/oclc/1010307875) to the document and our list of references.

**Comment by r12a** [comment]
These changes look good to me, and i like that the approach to the historical information is a little more systematic.

**Comment by shervinafshar** [comment]
Yeah. Looks good to me too. Waiting for response regarding citation before we can merge.

**Comment by shervinafshar** [comment]
@ntounsi, since this section was mostly your text, I added you as a reviewer as well. Please share your thoughts. Thanks.

**Comment by TitusNemeth** [comment]
Hi Shervin,

I am awfully sorry, I forgot that I set up a server-side filter that put all alreq mails in a dedicated folder, so didn’t see your replies until now. Sorry for that.

To answer your question: no, my book is specifically about the 20th century and mechanical (machine) typography and its influences on Arabic type design. It may still be a relevant reference<https://brill.com/view/title/32317>. For the section on writing styles I consulted mainly on Gacek’s Vademecum<https://brill.com/view/title/14879> and Blair’s Islamic Calligraphy<https://edinburghuniversitypress.com/book-islamic-calligraphy.html>.

Best
Titus

**Comment by shervinafshar** [comment]
Thank you, Titus. I'll add those to our list of references (currently maintained in a spreadsheet): https://docs.google.com/spreadsheets/d/137j59fPt1nkl0h6O72SR50SX3MHk0lWzmqcEaAmo1zM/edit#gid=0

**Review by shervinafshar — APPROVED** [review]

**Comment by TitusNemeth** [comment]
Excellent, thank you Shervin.
Titus

**Pull request merged**
