### PR TITLE
Add Shekasteh Nastaliq to writing styles section

### PR DESCRIPTION
**Pull request by ebraminio**
Used or can be used references:
- https://fa.wikipedia.org/wiki/خط_شکسته‌نستعلیق
- https://en.wikipedia.org/wiki/Nastaʿlīq_script#Shikasta_Nasta.CA.BFl.C4.ABq
- http://sadmu.ir/upload/Topic/14651.pdf
- https://commons.wikimedia.org/wiki/File:Ghafeleye_Omr.svg

### CODE REVIEW

**Comment by shervinafshar** [comment]
Thanks for the submissions, @ebraminio. Do you happen to have a source for Ta'liq image you submitted?

**Comment by ebraminio** [comment]
Yes, both images are from Wikipedia and Ta'liq one is from here https://commons.wikimedia.org/wiki/File:Ta%27liq_script_1.jpg

**Comment by zoghal** [comment]
@shervinafshar hi shervin, 
I got a great collection of pictures and e-books on the Arabic / Farsi.
You can see at this address: [HEre](https://drive.google.com/drive/folders/0B63aUENCmKIOT3R6ZGpDOHRNZk0?usp=sharing)
Maybe a lot of images that need to exist in this collection.

**Comment by shervinafshar** [comment]
Thanks, @zoghal, for pointing to your collection of documents and images. We certainly will take a look and pick the ones relevant to the text for the document and clear source information.

**Comment by shervinafshar** [comment]
@ebraminio, we discussed this in the meeting, and the opinion is just to add a small sentence to Nastaliq definition to mention Shekasteh Nastaliq as successor and subset of Nastaliq. Since our focus of document is not majorly on calligraphy, dedicated an independent section to Shekasteh would be out of our scope.

If you update the PR, we can revisit it next week and merge. Thanks again for your contribution.

**Comment by ebraminio** [comment]
Done. I hoped we could have both examples but it doesn't seem there would be enough room for both so I removed the added Shekasteh example.

**Comment by shervinafshar** [comment]
Shervin needs to edit the Shekasteh intro sentence a bit.

**Pull request merged**
